services:

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq-container
    hostname: rabbitmq-host
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-deploy-service

  config-server:
    image: asocarras/config-server:s6
    container_name: config-server-container
    ports:
      - 8071:8071
    depends_on:
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  accounts-service:
    image: asocarras/accounts-service:s6
    container_name: accounts-service-container
    ports:
      - 8080:8080
    extends:
      file: common-config.yml
      service: microservice-config-server-config
    environment:
      SPRING_APPLICATION_NAME: accounts-service

  loans-service:
    image: asocarras/loans-service:s6
    container_name: loans-service-container
    ports:
      - 8090:8090
    extends:
      file: common-config.yml
      service: microservice-config-server-config
    environment:
      SPRING_APPLICATION_NAME: loans-service

  cards-service:
    image: asocarras/cards-service:s6
    container_name: cards-service-container
    ports:
      - 9000:9000
    extends:
      file: common-config.yml
      service: microservice-config-server-config
    environment:
      SPRING_APPLICATION_NAME: cards-service

networks:
  eazybank:
    driver: bridge